# Generated by Django 5.2.8 on 2025-11-20 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=50)),
                ('legs', models.PositiveIntegerField()),
                ('started_at', models.BigIntegerField()),
                ('ended_at', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=50)),
                ('finish_on', models.PositiveIntegerField()),
                ('started_at', models.BigIntegerField()),
                ('ended_at', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dart1', models.PositiveIntegerField(blank=True, null=True)),
                ('dart2', models.PositiveIntegerField(blank=True, null=True)),
                ('dart3', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='darts_scores_backend_api.practicematch')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('leg', models.PositiveIntegerField()),
                ('darts_used_on_double', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='darts_scores_backend_api.match')),
            ],
        ),
    ]
