# Generated by Django 6.0 on 2025-12-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts_scores_backend_api', '0003_alter_match_user_alter_practicematch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='player',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
