# Generated by Django 6.0 on 2025-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts_scores_backend_api', '0004_match_players_turn_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='player',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
