# Generated by Django 6.0 on 2025-12-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts_scores_backend_api', '0005_alter_turn_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='leg_won',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
