# Generated by Django 6.0.1 on 2026-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts_scores_backend_api', '0006_turn_leg_won'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='practicematch',
            options={'verbose_name_plural': 'PracticeMatches'},
        ),
        migrations.AlterField(
            model_name='practiceturn',
            name='dart1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practiceturn',
            name='dart2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practiceturn',
            name='dart3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
